### ISSUE TITLE
Scary error message

### ISSUE THREAD

**Issue by jllang** [ucsd-progsys/liquidhaskell-blog#10]
I downloaded the LiquidHaskell book from the website (the link to the tutorial at `https://ucsd-progsys.github.io/lh-workshop/book.pdf` did not work). I installed Z3 version 4.4.1 (from Oct 2015) using apt-get in my Debian 10 system. I followed the instructions and managed to complete all exercises up to 2.3. (By the way, it wasn't entirely clear to me if I was supposed to complete the exercises by changing the code or the type definitions.) After completing exercise 2.3 I now get the following error:
```
**** LIQUID: ERROR :1:1-1:1: Error
  elaborate solver elabBE 288 "lq_anf$##7205759403792804453##d2P3" {lq_tmp$x##1799 : (GHC.Types.Any (GHC.Prim.TYPE GHC.Types.LiftedRep)) | [(lq_tmp$x##1799 = lq_anf$##7205759403792804452##d2P2);
                                                                         (lq_tmp$x##1799 = (GHC.Num.fromInteger lq_anf$##7205759403792804452##d2P2));
                                                                         (lq_tmp$x##1799 = (GHC.Num.fromInteger lq_anf$##7205759403792804452##d2P2))]} failed on:
      ((lq_tmp$x##1799 == lq_anf$##7205759403792804452##d2P2
        && lq_tmp$x##1799 == GHC.Num.fromInteger lq_anf$##7205759403792804452##d2P2)
       && lq_tmp$x##1799 == GHC.Num.fromInteger lq_anf$##7205759403792804452##d2P2)
  with error
      The sort (GHC.Types.Any (GHC.Prim.TYPE GHC.Types.LiftedRep)) is not numeric
  because
Cannot unify (GHC.Types.Any (GHC.Prim.TYPE GHC.Types.LiftedRep)) with int in expression: lq_tmp$x##1799 == lq_anf$##7205759403792804452##d2P2 
  because
Elaborate fails on lq_tmp$x##1799 == lq_anf$##7205759403792804452##d2P2
  in environment
      GHC.Num.fromInteger := func(1 , [int; @(0)])

      lq_anf$##7205759403792804452##d2P2 := int

      lq_tmp$x##1799 := (GHC.Types.Any (GHC.Prim.TYPE GHC.Types.LiftedRep)) 


--  While building package liquidhaskell-tutorial-0.2.0.0 (scroll up to its section to see the error) using:
      ~/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.2.0.0_ghc-8.10.1 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.2.0.0 build lib:liquidhaskell-tutorial --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
Type help for available commands. Press enter to force a rebuild.
```

**Comment by jllang** [comment]
The error message looks internal to me. Or is it something that I did in the exercise that could be the cause?

**Comment by jllang** [comment]
Sorry, I'm not sure if this issue went to the right repo. I used the link on the website.

**Comment by ranjitjhala** [comment]
Yikes - any chance you can post the code that triggers this error?

**Comment by jllang** [comment]
I was doing exercise 2.3 on page 26 of the PDF version of the book. This is the piece of code given in the exercise: 
```
{-@ ax6 :: Int -> Int -> TRUE @-}
ax6 x y = True==>(x<=x+y)
```
If I change the left-hand side of the implication `==>` I get that strange error.

**Comment by jllang** [comment]
I added parentheses around my left-hand side expression and now the error went away.

**Comment by yanhasu** [comment]
@jllang this sounds like a case of ucsd-progsys/liquidhaskell#1847.
i.e. there may be a 'normal' GHC error which LH is hiding (and you can uncover by turning off LH temporarily).

**Comment by jllang** [comment]
@yanhasu It looks like my report is a duplicate, so I'll close this one.
