### ISSUE TITLE
rss feed

### ISSUE THREAD

**Issue by rdesfo** [ucsd-progsys/liquidhaskell-blog#4]
I'd like to follow your blog but you don't offer a [rss feed](https://jaspervdj.be/hakyll/tutorials/05-snapshots-feeds.html).

**Comment by tfausak** [comment]
:+1: I would also like this!

**Comment by ranjitjhala** [comment]
I just added an "atom" feed; can you let me know if it works?

**Comment by tfausak** [comment]
Looks great! Thank you! 
https://ucsd-progsys.github.io/liquidhaskell-blog/atom.xml

**Comment by ranjitjhala** [comment]
how odd, that very link was not working despite

multiple page reloads (but now it is :))

perhaps some github pages caching issue.

oh well!

**Comment by ranjitjhala** [comment]
Closed by 8b07dbb0fec5226aa0f566d8333b711142f7ec6e
