### ISSUE TITLE
Almost entirely missing text on "Tutorial"

### ISSUE THREAD

**Issue by googleson78** [ucsd-progsys/liquidhaskell-blog#8]
The link titled [Tutorial](http://ucsd-progsys.github.io/lh-workshop/) in the blog has its paragraph text missing(?). Here's how it looks:
![broken](https://adjoint.fun/transfer/broken_blog.png)

**Comment by ranjitjhala** [comment]
Hmm not following -- can you post a screenshot of the place that's missing text? Thanks!

**Comment by googleson78** [comment]
Ah! I was under the wrong impression that I was missing some text (where the selection is in the OP image). Sorry!
