### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by mbrodersen** [ucsd-progsys/liquidhaskell-blog#9]
'$ cabal install liquidhaskell
Resolving dependencies...
Configuring liquidhaskell-0.8.0.5...
Building liquidhaskell-0.8.0.5...
Failed to install liquidhaskell-0.8.0.5
Build log ( /home/morten/.cabal/logs/liquidhaskell-0.8.0.5.log ):
cabal: Entering directory '/tmp/cabal-tmp-14418/liquidhaskell-0.8.0.5'
Configuring liquidhaskell-0.8.0.5...
Building liquidhaskell-0.8.0.5...
Preprocessing library liquidhaskell-0.8.0.5...
[  1 of 106] Compiling Test.Target.Expr ( src/Test/Target/Expr.hs, dist/build/Test/Target/Expr.o )
[  2 of 106] Compiling Paths_liquidhaskell ( dist/build/autogen/Paths_liquidhaskell.hs, dist/build/Paths_liquidhaskell.o )
[  3 of 106] Compiling Language.Haskell.Liquid.UX.Config ( src/Language/Haskell/Liquid/UX/Config.hs, dist/build/Language/Haskell/Liquid/UX/Config.o )
[  4 of 106] Compiling Language.Haskell.Liquid.Types.Variance ( src/Language/Haskell/Liquid/Types/Variance.hs, dist/build/Language/Haskell/Liquid/Types/Variance.o )
[  5 of 106] Compiling Language.Haskell.Liquid.Types.Specifications ( src/Language/Haskell/Liquid/Types/Specifications.hs, dist/build/Language/Haskell/Liquid/Types/Specifications.o )
[  6 of 106] Compiling Language.Haskell.Liquid.Types.Names ( src/Language/Haskell/Liquid/Types/Names.hs, dist/build/Language/Haskell/Liquid/Types/Names.o )
[  7 of 106] Compiling Language.Haskell.Liquid.ProofCombinators ( include/Language/Haskell/Liquid/ProofCombinators.hs, dist/build/Language/Haskell/Liquid/ProofCombinators.o )
[  8 of 106] Compiling Language.Haskell.Liquid.Prelude ( include/Language/Haskell/Liquid/Prelude.hs, dist/build/Language/Haskell/Liquid/Prelude.o )
[  9 of 106] Compiling Language.Haskell.Liquid.Misc ( src/Language/Haskell/Liquid/Misc.hs, dist/build/Language/Haskell/Liquid/Misc.o )

src/Language/Haskell/Liquid/Misc.hs:224:14: error:
    Ambiguous occurrence ‘=>>’
    It could refer to either ‘Language.Fixpoint.Misc.=>>’,
                             imported from ‘Language.Fixpoint.Misc’ at src/Language/Haskell/Liquid/Misc.hs:24:1-39
                          or ‘Language.Haskell.Liquid.Misc.=>>’,
                             defined at src/Language/Haskell/Liquid/Misc.hs:221:1
cabal: Leaving directory '/tmp/cabal-tmp-14418/liquidhaskell-0.8.0.5'
cabal: Error: some packages failed to install:
liquidhaskell-0.8.0.5 failed during the building phase. The exception was:
ExitFailure 1'

**Comment by mbrodersen** [comment]
Ubuntu 18.04
haskell-platform (GHC 8.0.2)

**Comment by ranjitjhala** [comment]
Hi @mbrodersen  -- that's a _super_ old version of LH, which seems to have hit some strange cabal problem. To avoid such issues I strongly advise installing it via `stack` as described here: 

https://github.com/ucsd-progsys/liquidhaskell/blob/develop/INSTALL.md#build-with-stack-recommended

**Comment by mbrodersen** [comment]
OK thanks I will try that :-)
